//bond price quoted as $1.05, where .05 represents 5/16. To convert this to decimal form:


DecimalPrice = DOLLARDE(1.05, 16)
//1.3125

FractionalPrice = DOLLARFR(1.3125, 16)
//1.05

// purchase a bond on January 1, 2023, with a maturity date of January 1, 2030.
// The bond pays a 5% annual coupon, has a 6% annual yield, and makes semiannual coupon payments.


BondDuration = DURATION(DATE(2023, 1, 1), DATE(2030, 1, 1), 0.05, 0.06, 2)