//Sales table - 01
Date	    SalesAmount
2024-08-01	100
2024-08-02	150
2024-09-01	200
2024-09-02	250

TotalSalesInRange = 
CALCULATE(
    SUM(Sales[SalesAmount]),
    DATESBETWEEN(Sales[Date], DATE(2024, 8, 1), DATE(2024, 8, 31))
)


//Sales table - 02
Category	SalesAmount
Electronics	500
Furniture	300
Clothing	200

TotalSalesAllCategories = 
CALCULATE(
    SUM(Sales[SalesAmount]),
    REMOVEFILTERS(Sales[Category])
)
