SafeDivision = 
IF(ISERROR(Sales[SalesAmount] / Sales[UnitsSold]), 
   BLANK(), 
   Sales[SalesAmount] / Sales[UnitsSold])

// SalesID	SalesAmount	UnitsSold
// 1	    500	        5
// 2	    300	        0


EvenSalesID = 
IF(ISEVEN(Sales[SalesID]), 
   "Even ID", 
   "Odd ID")

// SalesID	SalesAmount
// 1	        500
// 2	        300
// 3	        700


CheckProductFilter = 
IF(ISFILTERED(Sales[ProductID]), 
   "Product Filter Applied", 
   "No Product Filter")
