// Interest rate: 5% per year (0.05)
// Present value: $1,000
// Future value: $2,000

PDURATION(0.05, 1000, 2000)
//5%

// Loan amount: $10,000
// Interest rate: 6% per year (0.06)
// Loan term: 5 years
// Payments are made annually (type = 0).

PMT(0.06, 5, 10000)


// Loan amount: $10,000
// Interest rate: 5% annual interest (0.05/12 = 0.004167 for monthly payments)
// Number of payments: 36 months (3 years)
// Period: 1st payment

PPMT(0.004167, 1, 36, 10000)